networks:
  default:
    name: 'insurance_company'
    
volumes:
  postgres:
    
services:
  postgres:
    image: 'postgres:17.0'
    container_name: 'insurance_company_postgres'
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'INSURANCE_COMPANY'